export interface PortfolioSlide {
  id: number;
  title1: string;      // exactly 10 characters
  title2: string;      // exactly 6 characters
  title3: string;      // exactly 9 characters
  description: string; // exactly 132 characters
  spec1Label: string;  // exactly 6 characters ("Optics")
  spec1Value: string;  // exactly 18 characters
  spec2Label: string;  // exactly 5 characters ("Logic")
  spec2Value: string;  // exactly 18 characters
  spec3Label: string;  // exactly 6 characters ("Motion")
  spec4Label: string;  // exactly 5 characters ("Build")
  spec3Value: string;  // exactly 17 characters
  spec4Value: string;  // exactly 24 characters
  graphicType: 'network' | 'matrix' | 'quantum' | 'sphere' | 'circuit' | 'vector' | 'grid' | 'spiral' | 'scan' | 'geometry';
}

export const PORTFOLIO_SLIDES: PortfolioSlide[] = [
  {
    id: 1,
    title1: "SOFON-Y //",
    title2: "MASTER",
    title3: "PORTFOLIO",
    description: "Crafting high-end digital systems and flawless user interfaces for web platforms that don't just exist—they lead. Build your vision.",
    spec1Label: "Optics",
    spec1Value: "React & TypeScript",
    spec2Label: "Logic",
    spec2Value: "Node.js & Postgres",
    spec3Label: "Motion",
    spec3Value: "60fps Canvas Loop",
    spec4Label: "Build",
    spec4Value: "Tailwind CSS & Animation",
    graphicType: "network"
  },
  {
    id: 2,
    title1: "ENGINE- //",
    title2: "CODED.",
    title3: "SOLUTIONS",
    description: "Architecting lightning-fast serverless pipelines and headless commerce engines with bulletproof security layouts. Expand your reach.",
    spec1Label: "Optics",
    spec1Value: "Vercel Web Deploys",
    spec2Label: "Logic",
    spec2Value: "Prisma & MySql DBs",
    spec3Label: "Motion",
    spec3Value: "Framer Motion Dev",
    spec4Label: "Build",
    spec4Value: "Serverless Edge Registry",
    graphicType: "matrix"
  },
  {
    id: 3,
    title1: "AESTHET //",
    title2: "VISUAL",
    title3: "FRONTIERS",
    description: "Designing high-fidelity creative systems that merge immersive three-dimensional spatial canvas math with tactile web interaction.",
    spec1Label: "Optics",
    spec1Value: "Three.js Shader FX",
    spec2Label: "Logic",
    spec2Value: "GLSL Shader Kernel",
    spec3Label: "Motion",
    spec3Value: "Fluid Flow Physic",
    spec4Label: "Build",
    spec4Value: "GPU Accelerated Platform",
    graphicType: "sphere"
  },
  {
    id: 4,
    title1: "COGNIT- //",
    title2: "AI-DEV",
    title3: "NETWORKS.",
    description: "Implementing server-side intelligence layers using advanced Google Gemini models to power contextual and real-time reactive engines.",
    spec1Label: "Optics",
    spec1Value: "Gemini Flash Model",
    spec2Label: "Logic",
    spec2Value: "Vector Db Semantic",
    spec3Label: "Motion",
    spec3Value: "Streaming Outputs",
    spec4Label: "Build",
    spec4Value: "Adaptive Agent Workflows",
    graphicType: "quantum"
  },
  {
    id: 5,
    title1: "SYSTEMS //",
    title2: "SECURE",
    title3: "DATABASES",
    description: "Structuring scalable relational database pipelines and bulletproof security layers to safeguard high-volume enterprise transactions.",
    spec1Label: "Optics",
    spec1Value: "Prisma Client Hubs",
    spec2Label: "Logic",
    spec2Value: "PostgreSQL Schemas",
    spec3Label: "Motion",
    spec3Value: "Realtime Pub Sub.",
    spec4Label: "Build",
    spec4Value: "Distributed Query Planes",
    graphicType: "circuit"
  },
  {
    id: 6,
    title1: "DEVOPS- //",
    title2: "STABLE",
    title3: "RELIABLES",
    description: "Orchestrating automated deployment loops, cloud infrastructure orchestration, and server reliability layers for seamless operations.",
    spec1Label: "Optics",
    spec1Value: "Docker Registry OS",
    spec2Label: "Logic",
    spec2Value: "Cloud Run Scaling.",
    spec3Label: "Motion",
    spec3Value: "Zero Downtime Ops",
    spec4Label: "Build",
    spec4Value: "GitHub Actions Pipelines",
    graphicType: "vector"
  },
  {
    id: 7,
    title1: "MOBILE- //",
    title2: "HYBRID",
    title3: "PLATFORMS",
    description: "Engineering beautiful local mobile software utilizing lightweight cross-platform environments and native responsive bridges.",
    spec1Label: "Optics",
    spec1Value: "React Native Cores",
    spec2Label: "Logic",
    spec2Value: "SQLite Local Stores",
    spec3Label: "Motion",
    spec3Value: "60fps Touch Gestur",
    spec4Label: "Build",
    spec4Value: "App Store Deploy Pipeline",
    graphicType: "grid"
  },
  {
    id: 8,
    title1: "STYLING //",
    title2: "CRAFT.",
    title3: "REFINEMTS",
    description: "Tailoring atomic design hierarchies with extreme focus on negative spatial balance, custom modern colors, and typography layout.",
    spec1Label: "Optics",
    spec1Value: "Tailwind CSS v4.00",
    spec2Label: "Logic",
    spec2Value: "Dynamic Font Sizes",
    spec3Label: "Motion",
    spec3Value: "Micro-Hover States",
    spec4Label: "Build",
    spec4Value: "Responsive Layout Engine",
    graphicType: "spiral"
  },
  {
    id: 9,
    title1: "APIS-X- //",
    title2: "STREAM",
    title3: "ENDPOINTS",
    description: "Formulating solid high-concurrency gateway endpoints and modular custom routers featuring fast asynchronous request control.",
    spec1Label: "Optics",
    spec1Value: "GraphQL GQL Schema",
    spec2Label: "Logic",
    spec2Value: "Express Middleware",
    spec3Label: "Motion",
    spec3Value: "Realtime WebSockets",
    spec4Label: "Build",
    spec4Value: "Enterprise Scale Routing",
    graphicType: "scan"
  },
  {
    id: 10,
    title1: "PERFOR- //",
    title2: "SPEED.",
    title3: "OPTIMIZES",
    description: "Analyzing render trees to minimize package payloads, remove rendering blocking items, and achieve absolute maximum performance.",
    spec1Label: "Optics",
    spec1Value: "Chrome DevTools Core",
    spec2Label: "Logic",
    spec2Value: "Lighthouse Audit OS",
    spec3Label: "Motion",
    spec3Value: "ZeroLayout Shifting",
    spec4Label: "Build",
    spec4Value: "Static Single Page Builds",
    graphicType: "geometry"
  },
  {
    id: 11,
    title1: "CRYPTO- //",
    title2: "SECURE",
    title3: "KEYSTORES",
    description: "Designing end-to-end token encryption engines and zero-knowledge client authentication systems with flawless security tokens.",
    spec1Label: "Optics",
    spec1Value: "Auth0 Cloud Systems",
    spec2Label: "Logic",
    spec2Value: "JWT Cryptography OS",
    spec3Label: "Motion",
    spec3Value: "Secure In-Memory..",
    spec4Label: "Build",
    spec4Value: "High compliance Web Vault",
    graphicType: "network"
  },
  {
    id: 12,
    title1: "SOCKETS //",
    title2: "ACTIVE",
    title3: "CHANNELS.",
    description: "Constructing multi-user collaboration layers with low millisecond latency updates and flawless server-authoritative state webs.",
    spec1Label: "Optics",
    spec1Value: "WebRTC Peer Streams",
    spec2Label: "Logic",
    spec2Value: "Socket.io Instances",
    spec3Label: "Motion",
    spec3Value: "Instant Sync Loops",
    spec4Label: "Build",
    spec4Value: "Multiplayer Engine Room.",
    graphicType: "matrix"
  },
  {
    id: 13,
    title1: "EDGE-D- //",
    title2: "GLOBAL",
    title3: "REPOSITOR",
    description: "Relocating heavy calculation pipelines to lightweight distributed worker environments right next to the active requesting clients.",
    spec1Label: "Optics",
    spec1Value: "Cloudflare Workers",
    spec2Label: "Logic",
    spec2Value: "Vercel Edge Routine",
    spec3Label: "Motion",
    spec3Value: "Localized Caching.",
    spec4Label: "Build",
    spec4Value: "Global Edge Content Hub.",
    graphicType: "sphere"
  },
  {
    id: 14,
    title1: "STATES- //",
    title2: "STABLE",
    title3: "FLOW-REUX",
    description: "Orchestrating state machines to track intricate web application transitions and guarantee bulletproof client-side reliability.",
    spec1Label: "Optics",
    spec1Value: "Zustand Store Engine",
    spec2Label: "Logic",
    spec2Value: "Redux Toolkit Hooks",
    spec3Label: "Motion",
    spec3Value: "State Machine Sync",
    spec4Label: "Build",
    spec4Value: "Deterministic UI Systems",
    graphicType: "quantum"
  },
  {
    id: 15,
    title1: "ARCHIT- //",
    title2: "SOLID.",
    title3: "STRUCTURE",
    description: "Refactoring legacy setups into modular clean structure systems with fully decoupled modules and pristine dependency hierarchies.",
    spec1Label: "Optics",
    spec1Value: "Monorepo Lerna Hubs",
    spec2Label: "Logic",
    spec2Value: "SOLID Coding Pattern",
    spec3Label: "Motion",
    spec3Value: "Decoupled Data Flow",
    spec4Label: "Build",
    spec4Value: "Highly Maintainable Bases",
    graphicType: "circuit"
  },
  {
    id: 16,
    title1: "TESTING //",
    title2: "SAFETY",
    title3: "ASSURANCE",
    description: "Executing massive automated test matrices across diverse browsers to prevent software regression and achieve complete resilience.",
    spec1Label: "Optics",
    spec1Value: "Playwright Test Run",
    spec2Label: "Logic",
    spec2Value: "Vitest Testing Suite",
    spec3Label: "Motion",
    spec3Value: "CI Triggered Tests",
    spec4Label: "Build",
    spec4Value: "100Percent Code Coverage",
    graphicType: "vector"
  },
  {
    id: 17,
    title1: "CREATIV //",
    title2: "MATHFX",
    title3: "CANVASSES",
    description: "Synthesizing trigonometric orbit functions and vector field simulations to craft unique interactive background graphics on web.",
    spec1Label: "Optics",
    spec1Value: "HTML5 Canvas Engine",
    spec2Label: "Logic",
    spec2Value: "Trig Math Calculat.",
    spec3Label: "Motion",
    spec3Value: "Euler Particle Flow",
    spec4Label: "Build",
    spec4Value: "Generative Art Playgrounds",
    graphicType: "spiral"
  },
  {
    id: 18,
    title1: "COLLAB- //",
    title2: "REMOTE",
    title3: "DEVELOPER",
    description: "Aligning distributed workspace contributors through meticulous code reviews, streamlined pull requests, and standard procedures.",
    spec1Label: "Optics",
    spec1Value: "GitHub Collaborates",
    spec2Label: "Logic",
    spec2Value: "Git Branching Model",
    spec3Label: "Motion",
    spec3Value: "Atomic Commits Flow",
    spec4Label: "Build",
    spec4Value: "Seamless Team Integration",
    graphicType: "grid"
  },
  {
    id: 19,
    title1: "DEVEXP- //",
    title2: "DESIGN",
    title3: "TOOLKITS.",
    description: "Configuring lightning-fast command line environments, customized format templates, and automated linter checkers for speed.",
    spec1Label: "Optics",
    spec1Value: "ESLint Configuration",
    spec2Label: "Logic",
    spec2Value: "Prettier Formatting",
    spec3Label: "Motion",
    spec3Value: "TSX Direct Execution",
    spec4Label: "Build",
    spec4Value: "Ultra Fast Developer Boot",
    graphicType: "scan"
  },
  {
    id: 20,
    title1: "PRODUCT //",
    title2: "VISION",
    title3: "STRATEGYS",
    description: "Bridging mechanical technical constraints with actual user needs to define perfect digital pipelines with immediate market fits.",
    spec1Label: "Optics",
    spec1Value: "User Persona Mapping",
    spec2Label: "Logic",
    spec2Value: "Agile Sprint Routine",
    spec3Label: "Motion",
    spec3Value: "Figma Asset Hand-off",
    spec4Label: "Build",
    spec4Value: "Rapid Prototyping Systems",
    graphicType: "geometry"
  },
  {
    id: 21,
    title1: "COMPIL- //",
    title2: "SERVER",
    title3: "RENDER-OS",
    description: "Leveraging static site generation and dynamic server components to fetch complex database records directly on initial requests.",
    spec1Label: "Optics",
    spec1Value: "NextJS Server Actions",
    spec2Label: "Logic",
    spec2Value: "Server Component DB",
    spec3Label: "Motion",
    spec3Value: "Streaming Server UI",
    spec4Label: "Build",
    spec4Value: "Fastest Initial Page Load",
    graphicType: "network"
  },
  {
    id: 22,
    title1: "VISUALS //",
    title2: "CHARTS",
    title3: "DATAPLOTS",
    description: "Mapping dense metric collections into elegant interactive charts and responsive SVG graphs featuring smooth hover tracking data.",
    spec1Label: "Optics",
    spec1Value: "Recharts Library UI",
    spec2Label: "Logic",
    spec2Value: "D3.js Scaling Math",
    spec3Label: "Motion",
    spec3Value: "SVG Interactive FX",
    spec4Label: "Build",
    spec4Value: "Real-time Telemetry Boards",
    graphicType: "matrix"
  },
  {
    id: 23,
    title1: "ACCESS- //",
    title2: "A11Y-Y",
    title3: "STANDARDS",
    description: "Implementing screen reader tags, robust speech commands, and full keyboard-focusable layout trees in strict WCAG compliance standards.",
    spec1Label: "Optics",
    spec1Value: "Semantic Html Layout",
    spec2Label: "Logic",
    spec2Value: "ARIA Tag Attributions",
    spec3Label: "Motion",
    spec3Value: "Reduced Motion State",
    spec4Label: "Build",
    spec4Value: "Completely Inclusive Design",
    graphicType: "sphere"
  },
  {
    id: 24,
    title1: "GLOBAL- //",
    title2: "LOCALS",
    title3: "TRANSLATE",
    description: "Setting up deep localization frameworks with instantaneous translation updates and automatic local datetime formatting schemas.",
    spec1Label: "Optics",
    spec1Value: "i18next Translators",
    spec2Label: "Logic",
    spec2Value: "RTL Layout Supports",
    spec3Label: "Motion",
    spec3Value: "Locale Detection OS",
    spec4Label: "Build",
    spec4Value: "Multi-Language Web Engine",
    graphicType: "quantum"
  },
  {
    id: 25,
    title1: "FUTURES //",
    title2: "WEB-3D",
    title3: "METAVERS.",
    description: "Exploring immersive virtual interfaces and responsive WebXR hardware hooks to structure spatial internet paradigms of tomorrow.",
    spec1Label: "Optics",
    spec1Value: "WebXR Device Adapters",
    spec2Label: "Logic",
    spec2Value: "Three Spatial Matrix",
    spec3Label: "Motion",
    spec3Value: "Head Tracking Routine",
    spec4Label: "Build",
    spec4Value: "Spatial Computing Systems",
    graphicType: "circuit"
  },
  {
    id: 26,
    title1: "INFINIT //",
    title2: "S-PORT",
    title3: "HORIZONS.",
    description: "Pushing full-stack digital development boundaries further with extreme performance, creative coding, and flawless user execution.",
    spec1Label: "Optics",
    spec1Value: "Creative Coding Hub",
    spec2Label: "Logic",
    spec2Value: "Core Dev Philosophy",
    spec3Label: "Motion",
    spec3Value: "Absolute Smooth FPS",
    spec4Label: "Build",
    spec4Value: "Endless Software Wonders",
    graphicType: "vector"
  }
];
